default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        name: ruff-all
        files: ^backend/(?!tests).*\.py$
        args: ["--config", "backend/pyproject.toml", "--fix"]

      - id: ruff
        name: ruff-imports
        files: ^backend/(?!tests).*\.py$
        args: ["--config", "backend/pyproject.toml", "--select", "I", "--fix"]

      - id: ruff-format
        files: ^backend/(?!tests).*\.py$
        args: ["--config", "backend/pyproject.toml"]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 5f9c312d9978fbcee1da97154ba385834eeda799
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
