services:
  backend:
    container_name: cryptoapp.api.dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-8000}:8000
    command: uvicorn cryptoapp.main.web:main --host 0.0.0.0 --port 8000 --reload --factory --use-colors
    volumes:
      - ./backend/src/cryptoapp:/app/cryptoapp
    depends_on:
      rabbit:
        condition: service_healthy

  frontend:
    container_name: cryptoapp.frontend.dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - "4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_started


  database:
    image: postgres:16.4-alpine
    container_name: cryptoapp.postgres.dev
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: cryptoapp.redis.dev
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./data/redis:/data
    command: redis-server --bind 0.0.0.0 --requirepass "$REDIS_PASSWORD" --appendonly yes --appendfsync everysec

  rabbit:
    image: rabbitmq:4.0-management
    container_name: cryptoapp.rabbitmq.dev
    ports:
      - ${RABBIT_PORT}:5672     # AMQP
      - "15672:15672"    # RabbitMQ Management UI
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s

  worker:
    container_name: cryptoapp.worker.dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    command: taskiq worker --ack-type when_saved cryptoapp.main.taskiq_entry.broker:setup_taskiq_broker cryptoapp.infrastructure.taskiq_tasks
    volumes:
      - ./backend/src/cryptoapp:/app/cryptoapp
    depends_on:
      rabbit:
        condition: service_healthy

  scheduler:
    container_name: cryptoapp.scheduler.dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    command: taskiq scheduler cryptoapp.main.taskiq_entry.broker:setup_taskiq_scheduler cryptoapp.infrastructure.taskiq_tasks
    volumes:
      - ./backend/src/cryptoapp:/app/cryptoapp
    depends_on:
      rabbit:
        condition: service_healthy

  nginx:
    container_name: cryptoapp.nginx.dev
    image: clandast/nginx-vts:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

  vector-agent:
    container_name: cryptoapp.vector-agent.dev
    image: timberio/vector:0.45.0-alpine
    privileged: true
    pid: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/vector.yaml:/etc/vector/vector.yaml:ro
      - /proc:/host_proc:ro
      - /sys:/host_sys:ro
    environment:
      PROCFS_ROOT: "/host_proc"
      SYSFS_ROOT: "/host_sys"
      HOSTNAME: "localhost"
    command: ["--config", "/etc/vector/vector.yaml"]

  vmagent:
    container_name: cryptoapp.vm-agent.dev
    image: victoriametrics/vmagent:v1.113.0
    depends_on:
      - "victoriametrics"
      - "nginx"
    ports:
      - "8429:8429"
    volumes:
      - vmagent_data:/vmagentdata
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yaml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    restart: always

  victoriametrics:
    container_name: cryptoapp.vmetrics.dev
    image: victoriametrics/victoria-metrics:v1.113.0
    ports:
      - "8428:8428"
    volumes:
      - vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
    restart: always

  victorialogs:
    container_name: cryptoapp.vlogs.dev
    image: victoriametrics/victoria-logs:v1.15.0-victorialogs
    ports:
      - "9428:9428"
    volumes:
       - victorialogs_data:/victoria-logs-data
    restart: always

  cadvisor:
    container_name: cryptoapp.cadvisor.dev
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices:
      - "/dev/kmsg"

  grafana:
    container_name: cryptoapp.grafana.dev
    image: grafana/grafana-oss:11.3.4
    environment:
      - GF_INSTALL_PLUGINS=victoriametrics-logs-datasource
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - victoriametrics
      - victorialogs
    restart: unless-stopped

  minio:
    container_name: cryptoapp.minio.dev
    image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z
    env_file:
      - .env
    ports:
      - "${MINIO_PORT}:9000"
      - "9001:9001"
    volumes:
    - minio-data:/data
    command: server /data --console-address :9001
    restart: unless-stopped


volumes:
  grafana_data:
  vmdata:
  vmagent_data:
  victorialogs_data:
  rabbitmq_data:
  minio-data: