services:
  backend:
    container_name: cryptoapp.api.dev
    image: cryptoapp_api:dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-8000}:8000
    command: uvicorn cryptoapp.main.web:create_app --host 0.0.0.0 --port 8000 --reload --factory
    volumes:
      - ./backend/src/cryptoapp:/app/cryptoapp
    depends_on:
      rabbit:
        condition: service_healthy

  database:
    image: postgres:16.4-alpine
    container_name: cryptoapp.postgres.dev
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: cryptoapp.redis.dev
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./data/redis:/data
    command: redis-server --bind 0.0.0.0 --requirepass "$REDIS_PASSWORD" --appendonly yes --appendfsync everysec

  rabbit:
    image: rabbitmq:4.0-management
    container_name: cryptoapp.rabbitmq.dev
    ports:
      - ${RABBIT_PORT}:5672     # AMQP
      - 15672:15672    # RabbitMQ Management UI
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s

  worker:
    container_name: cryptoapp.worker.dev
    image: cryptoapp_api:dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    command: taskiq worker --ack-type when_saved cryptoapp.main.taskiq_entry.broker:broker cryptoapp.presentation.task_executor.tasks
    volumes:
      - ./backend/src/cryptoapp:/app/cryptoapp
    depends_on:
      rabbit:
        condition: service_healthy

  nginx:
    container_name: cryptoapp.nginx.dev
    image: clandast/nginx-vts:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend:
        condition: service_started

  vector-agent:
    container_name: cryptoapp.vector.dev
    image: timberio/vector:0.45.0-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/vector.yml:/etc/vector/vector.yml:ro
      - ./logs/cryptoapp_filtered.log:/var/log/cryptoapp_filtered.log
    command: ["--config", "/etc/vector/vector.yml"]
