services:
  pg_test_database:
    image: postgres:16-alpine
    ports:
      - "5440:5432"
    restart: always
    volumes:
      - pgtestdata:/var/lib/postgresql/data
    env_file:
      - '.env'
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

#  api:
#    image: "api"
#    stop_signal: SIGINT
#    build:
#      context: backend
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
#    restart: always
#    env_file:
#      - ".env"
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "200k"
#        max-file: "10"
#    volumes:
#      - ./backend/src/cryptoapp:/app/src/cryptoapp

volumes:
  pgtestdata:
