[project]
name = "cryptoapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Krak3nDev", email = "bihichnazar@gmail.com" }
]
requires-python = ">=3.11"

dependencies = [
    "aiosmtplib>=4.0.0",
    "alembic>=1.14.1",
    "bcrypt>=4.2.1",
    "colorlog>=6.9.0",
    "dishka>=1.4.2",
    "environs>=14.1.1",
    "fastapi[standard]>=0.115.8",
    "orjson>=3.10.15",
    "psycopg[binary]>=3.2.4",
    "redis>=5.2.1",
    "sqlalchemy>=2.0.38",
    "taskiq[orjson]>=0.11.11",
    "taskiq-aio-pika>=0.4.1",
    "taskiq-redis>=1.0.2",
]


[dependency-groups]
lint = [
    "mypy>=1.15.0",
    "ruff>=0.9.6",
]


[tool.ruff]
line-length = 88
indent-width = 4

target-version = "py311"


[lint]
select = ["E4", "E7", "E9", "F", "E501", "I"]
ignore = []
fixable = ["ALL"]

[lint.isort]
case-sensitive = true

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"


exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]



[tool.mypy]
disallow_subclassing_any = false
ignore_missing_imports = true
disable_error_code = "import-untyped,misc"
strict = true
exclude = [
    "\\.git",
    "\\.venv",
    "\\.idea",
    "tests/",
    "\\.cache",
    "build",
    "dist",
    "scripts",
]




[project.scripts]
cryptoapp = "cryptoapp:main"

[tool.hatch.build.targets.wheel]
packages = ["src/cryptoapp"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
