[project]
name = "cryptoapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Krak3nDev", email = "bihichnazar@gmail.com" }
]
requires-python = ">=3.12"

dependencies = [
    "aioboto3>=14.1.0",
    "aiosmtplib>=4.0.0",
    "alembic>=1.14.1",
    "bcrypt>=4.2.1",
    "colorlog>=6.9.0",
    "dishka>=1.4.2",
    "environs>=14.1.1",
    "fastapi[standard]>=0.115.8",
    "httpx>=0.28.1",
    "orjson>=3.10.15",
    "pillow>=11.1.0",
    "psycopg[binary]>=3.2.4",
    "python-multipart>=0.0.20",
    "redis>=5.2.1",
    "sqlalchemy>=2.0.38",
    "taskiq-aio-pika>=0.4.1",
    "taskiq-redis>=1.0.2",
    "taskiq[orjson]>=0.11.11",
    "tenacity>=9.0.0",
    "uuid6>=2024.7.10",
]

[dependency-groups]
dev = [
    "testcontainers[minio,postgres,rabbitmq,redis]>=4.10.0",
    "mypy>=1.15.0",
    "ruff>=0.11.2",
    "pytest-asyncio>=0.25.3",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
]

[tool.ruff]
line-length = 79
indent-width = 4

target-version = "py311"


[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "E501", "I"]
ignore = []
fixable = ["ALL"]


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"


exclude = [
    "tests/",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]



[tool.mypy]
disallow_subclassing_any = false
ignore_missing_imports = true
disable_error_code = "import-untyped,misc"
strict = true
exclude = [
    "\\.git",
    "\\.venv",
    "\\.idea",
    "tests/",
    "\\.cache",
    "build",
    "dist",
    "scripts",
]


[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "session"


[project.scripts]
cryptoapp = "cryptoapp:main"

[tool.hatch.build.targets.wheel]
packages = ["src/cryptoapp"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
