"""update transaction table

Revision ID: 5eb54ca62c4c
Revises: e4195d799165
Create Date: 2025-03-23 18:58:12.151627

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5eb54ca62c4c"
down_revision: Union[str, None] = "e4195d799165"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("quantity", sa.Numeric(precision=38, scale=8), nullable=False),
    )
    op.add_column(
        "transactions",
        sa.Column("price", sa.Numeric(precision=38, scale=12), nullable=True),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.alter_column(
        "transactions",
        "transaction_type",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.drop_column("transactions", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "date",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "transactions",
        "transaction_type",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    op.drop_column("transactions", "created_at")
    op.drop_column("transactions", "price")
    op.drop_column("transactions", "quantity")
    # ### end Alembic commands ###
