"""add portfolio, transaction, tags, asset tables

Revision ID: e4195d799165
Revises: cec17d580da2
Create Date: 2025-03-22 14:22:30.472365

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4195d799165"
down_revision: Union[str, None] = "cec17d580da2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("asset_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cmc_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=True),
        sa.Column("date_added", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "is_infinite_supply", sa.Boolean(), server_default="0", nullable=False
        ),
        sa.Column("max_supply", sa.Numeric(precision=38, scale=6), nullable=True),
        sa.Column("total_supply", sa.Numeric(precision=38, scale=6), nullable=True),
        sa.Column(
            "circulating_supply", sa.Numeric(precision=38, scale=6), nullable=True
        ),
        sa.Column("price_usd", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("volume_24h_usd", sa.Numeric(precision=38, scale=2), nullable=True),
        sa.Column("market_cap_usd", sa.Numeric(precision=38, scale=2), nullable=True),
        sa.Column(
            "percent_change_1h_usd", sa.Numeric(precision=15, scale=5), nullable=True
        ),
        sa.Column(
            "percent_change_24h_usd", sa.Numeric(precision=15, scale=5), nullable=True
        ),
        sa.Column(
            "percent_change_7d_usd", sa.Numeric(precision=15, scale=5), nullable=True
        ),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("asset_id", name=op.f("pk_assets")),
        sa.UniqueConstraint("cmc_id", name=op.f("uq_assets_cmc_id")),
    )
    op.create_table(
        "tags",
        sa.Column("tag_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("tag_id", name=op.f("pk_tags")),
        sa.UniqueConstraint("name", name=op.f("uq_tags_name")),
    )
    op.create_table(
        "assets_tags",
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.asset_id"],
            name=op.f("fk_assets_tags_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.tag_id"],
            name=op.f("fk_assets_tags_tag_id_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("asset_id", "tag_id", name=op.f("pk_assets_tags")),
    )
    op.create_table(
        "portfolios",
        sa.Column("portfolio_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("avatar", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_portfolios_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("portfolio_id", name=op.f("pk_portfolios")),
    )
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("transaction_type", sa.String(length=10), nullable=False),
        sa.Column("fee", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.asset_id"],
            name=op.f("fk_transactions_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.portfolio_id"],
            name=op.f("fk_transactions_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("transaction_id", name=op.f("pk_transactions")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("portfolios")
    op.drop_table("assets_tags")
    op.drop_table("tags")
    op.drop_table("assets")
    # ### end Alembic commands ###
