sources:
  docker_logs_source:
    type: docker_logs
    include_containers:
      - "cryptoapp.api.dev"
      - "cryptoapp.worker.dev"

transforms:
  remap_logs:
    type: remap
    inputs:
      - docker_logs_source
    source: |
      .level = if exists(.level) && !is_null(.level) {
          .level
      } else if exists(.severity) && !is_null(.severity) {
          .severity
      } else {
          "INFO"
      }

      .count = 1

      .

  filter_logs:
    type: filter
    inputs:
      - remap_logs
    condition: "true"

  mark_send_mail:
    type: remap
    inputs:
      - filter_logs
    source: |
      .is_send_mail = contains!(.message, "Executing task send_mail")
      .

  filter_send_mail:
    type: filter
    inputs:
      - mark_send_mail
    condition: '.is_send_mail == true'

  logs_to_metric_send_mail:
    type: log_to_metric
    inputs:
      - filter_send_mail
    metrics:
      - type: counter
        name: "send_mail_count"
        description: "Number of times the send_mail task was executed"
        field: count
        tags:
          container: "{{ container_name }}"

  logs_to_metric:
    type: log_to_metric
    inputs:
      - filter_logs
    metrics:
      - type: counter
        name: "cryptoapp_log_count"
        description: "Number of log messages that passed the filter"
        field: count
        tags:
          container: "{{ container_name }}"
      - type: counter
        name: "cryptoapp_logs_by_level"
        description: "Number of log messages that passed the filter"
        field: count
        tags:
          container: "{{ container_name }}"
          level: "{{ level }}"

sinks:
  victoriametrics_sink:
    type: prometheus_remote_write
    inputs:
      - logs_to_metric
      - logs_to_metric_send_mail
    endpoint: "http://victoriametrics:8428/api/v1/write"
    healthcheck:
      enabled: false

  victoria_logs_sink:
    type: elasticsearch
    inputs:
      - filter_logs
    endpoints:
      - "http://victorialogs:9428/insert/elasticsearch/"
    api_version: v8
    compression: gzip
    healthcheck:
      enabled: false
    query:
      _msg_field: message
      _time_field: timestamp
      _stream_fields: host,container_name
      debug: true
