export const testData = [
  {
    name: "Bitcoin BTC",
    image: "https://cryptologos.cc/logos/bitcoin-btc-logo.png",
    price: 55105.68,
    change1h: 0.51,
    change24h: 6.29,
    change7d: -17.22,
  },
  {
    name: "Ethereum ETH",
    image: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
    price: 2455.2,
    change1h: 0.18,
    change24h: 7.67,
    change7d: -26.36,
  },
  {
    name: "Tether USDT",
    image: "https://cryptologos.cc/logos/tether-usdt-logo.png",
    price: 1.0,
    change1h: -0.07,
    change24h: 0.01,
    change7d: 0.05,
  },
  {
    name: "BNB BNB",
    image: "https://cryptologos.cc/logos/bnb-bnb-logo.png",
    price: 480.13,
    change1h: 0.24,
    change24h: 9.11,
    change7d: -16.15,
  },
  {
    name: "Solana SOL",
    image: "https://cryptologos.cc/logos/solana-sol-logo.png",
    price: 138.58,
    change1h: 0.95,
    change24h: 16.32,
    change7d: -23.66,
  },
  {
    name: "USDC USDC",
    image: "https://cryptologos.cc/logos/usd-coin-usdc-logo.png",
    price: 1.0,
    change1h: -0.06,
    change24h: 0.03,
    change7d: 0.0,
  },
  {
    name: "XRP XRP",
    image: "https://cryptologos.cc/logos/xrp-xrp-logo.png",
    price: 0.5015,
    change1h: -0.54,
    change24h: 8.33,
    change7d: -17.1,
  },
]
